# Generated by Django 4.2.27 on 2026-01-31 17:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_romaneio', models.CharField(db_index=True, help_text='Ex: 11613, 11627', max_length=20, unique=True)),
                ('data_romaneio', models.DateField(db_index=True, verbose_name='Data do Romaneio')),
                ('tipo_romaneio', models.CharField(choices=[('NORMAL', 'Normal'), ('COM_FRETE', 'Com Frete')], default='NORMAL', max_length=15, verbose_name='Tipo do Romaneio')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Valor Total')),
                ('m3_total', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10, verbose_name='Volume Total (m³)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios', to='cadastros.cliente', verbose_name='Cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios', to='cadastros.motorista', verbose_name='Motorista')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Cadastro')),
            ],
            options={
                'verbose_name': 'Romaneio',
                'verbose_name_plural': 'Romaneios',
                'ordering': ['-data_romaneio', '-numero_romaneio'],
            },
        ),
        migrations.CreateModel(
            name='ItemRomaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_m3', models.DecimalField(decimal_places=3, help_text='Quantidade em metros cúbicos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade (m³)')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor por m³', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário (R$/m³)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Valor Total')),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='romaneio.romaneio', verbose_name='Romaneio')),
                ('tipo_madeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_romaneio', to='cadastros.tipomadeira', verbose_name='Tipo de Madeira')),
            ],
            options={
                'verbose_name': 'Item do Romaneio',
                'verbose_name_plural': 'Itens do Romaneio',
                'ordering': ['romaneio', 'tipo_madeira'],
            },
        ),
        migrations.AddIndex(
            model_name='romaneio',
            index=models.Index(fields=['data_romaneio', 'cliente'], name='romaneio_ro_data_ro_e431f6_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneio',
            index=models.Index(fields=['numero_romaneio'], name='romaneio_ro_numero__a65edb_idx'),
        ),
    ]
