# Generated by Django 4.2.27 on 2026-02-03 03:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('romaneio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRomaneioDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comprimento')),
                ('rodo', models.CharField(blank=True, max_length=20)),
                ('quantidade_m3', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
            ],
            options={
                'verbose_name': 'Item do Romaneio Detalhado',
                'verbose_name_plural': 'Itens do Romaneio Detalhado',
                'ordering': ['romaneio', 'tipo_madeira'],
            },
        ),
        migrations.CreateModel(
            name='RomaneioDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_romaneio', models.CharField(db_index=True, max_length=20, unique=True)),
                ('data_romaneio', models.DateField(db_index=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de desconto (0 ~ 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('m3_total', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Romaneio Detalhado',
                'verbose_name_plural': 'Romaneios Detalhados',
                'ordering': ['-data_romaneio', '-numero_romaneio'],
            },
        ),
        migrations.RemoveIndex(
            model_name='romaneio',
            name='romaneio_ro_data_ro_e431f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='romaneio',
            name='romaneio_ro_numero__a65edb_idx',
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='quantidade_m3',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='romaneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='romaneio.romaneio'),
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='tipo_madeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_romaneio', to='cadastros.tipomadeira'),
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios', to='cadastros.cliente'),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='data_romaneio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='m3_total',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios', to='cadastros.motorista'),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='numero_romaneio',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='tipo_romaneio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('COM_FRETE', 'Com Frete')], default='NORMAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='romaneiodetalhado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_detalhados', to='cadastros.cliente'),
        ),
        migrations.AddField(
            model_name='romaneiodetalhado',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_detalhados', to='cadastros.motorista'),
        ),
        migrations.AddField(
            model_name='romaneiodetalhado',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_detalhados_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemromaneiodetalhado',
            name='romaneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='romaneio.romaneiodetalhado'),
        ),
        migrations.AddField(
            model_name='itemromaneiodetalhado',
            name='tipo_madeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_romaneio_detalhado', to='cadastros.tipomadeira'),
        ),
    ]
