# Generated by Django 4.2.27 on 2026-02-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0002_itemromaneiodetalhado_romaneiodetalhado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneiodetalhado',
            name='tipo_romaneio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('COM_FRETE', 'Com Frete')], default='NORMAL', max_length=15),
        ),
    ]
