# Generated by Django 4.2.27 on 2026-02-05 03:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0003_romaneiodetalhado_tipo_romaneio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemromaneio',
            options={'ordering': ['romaneio', 'tipo_madeira', 'id'], 'verbose_name': 'Item do Romaneio', 'verbose_name_plural': 'Itens do Romaneio'},
        ),
        migrations.AlterModelOptions(
            name='itemromaneiodetalhado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='romaneiodetalhado',
            options={},
        ),
        migrations.AddField(
            model_name='itemromaneio',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comprimento'),
        ),
        migrations.AddField(
            model_name='itemromaneio',
            name='rodo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='modalidade',
            field=models.CharField(choices=[('SIMPLES', 'Simples'), ('DETALHADO', 'Detalhado')], default='SIMPLES', max_length=10),
        ),
        migrations.AddField(
            model_name='romaneio',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemromaneiodetalhado',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='romaneiodetalhado',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
