# Generated by Django 4.2.27 on 2026-02-05 04:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0005_migrar_romaneio_detalhado_para_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='romaneiodetalhado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='romaneiodetalhado',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='romaneiodetalhado',
            name='usuario_cadastro',
        ),
        migrations.AlterField(
            model_name='romaneio',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual (0 ~ 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.DeleteModel(
            name='ItemRomaneioDetalhado',
        ),
        migrations.DeleteModel(
            name='RomaneioDetalhado',
        ),
    ]
