# Generated by Django 4.2.27 on 2026-02-06 01:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0006_remove_romaneiodetalhado_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemromaneio',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='itemromaneio',
            name='quantidade_m3',
        ),
        migrations.RemoveField(
            model_name='itemromaneio',
            name='rodo',
        ),
        migrations.RemoveField(
            model_name='romaneio',
            name='desconto',
        ),
        migrations.AddField(
            model_name='itemromaneio',
            name='quantidade_m3_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=10, verbose_name='Total m³'),
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemromaneio',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor/m³'),
        ),
        migrations.CreateModel(
            name='UnidadeRomaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, help_text='Em metros', max_digits=6, null=True, verbose_name='Comprimento (m)')),
                ('rodo', models.DecimalField(blank=True, decimal_places=2, help_text='Em centímetros', max_digits=6, null=True, verbose_name='Rôdo (cm)')),
                ('desconto_1', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Em centímetros', max_digits=6, null=True, verbose_name='Desconto 1 (cm)')),
                ('desconto_2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Em centímetros', max_digits=6, null=True, verbose_name='Desconto 2 (cm)')),
                ('quantidade_m3', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade (m³)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='romaneio.itemromaneio')),
            ],
            options={
                'verbose_name': 'Unidade do Romaneio',
                'verbose_name_plural': 'Unidades do Romaneio',
                'ordering': ['item', 'id'],
            },
        ),
    ]
