# Generated by Django 4.2.27 on 2026-02-06 02:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0007_remove_itemromaneio_comprimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemromaneio',
            name='quantidade_m3_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Total m³'),
        ),
        migrations.AlterField(
            model_name='unidaderomaneio',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comprimento (m)'),
        ),
        migrations.AlterField(
            model_name='unidaderomaneio',
            name='desconto_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='unidaderomaneio',
            name='desconto_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='unidaderomaneio',
            name='rodo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rôdo (cm)'),
        ),
    ]
