# Generated by Django 4.2.27 on 2026-02-09 22:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romaneio', '0008_alter_itemromaneio_quantidade_m3_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneio',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de desconto aplicado sobre o valor bruto (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
