# Generated by Django 4.2.27 on 2026-06-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_romaneiador'),
        ('romaneio', '0009_romaneio_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneio',
            name='romaneiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios', to='cadastros.romaneiador'),
        ),
    ]
