# Generated by Django 4.2.27 on 2026-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Chave/Nome')),
                ('valor', models.CharField(max_length=500, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
                'ordering': ['nome'],
            },
        ),
    ]
