# Generated by Django 4.2.27 on 2026-01-31 17:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(db_index=True, verbose_name='Data do Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('tipo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito'), ('OUTROS', 'Outros')], default='DINHEIRO', max_length=20, verbose_name='Tipo de Pagamento')),
                ('descricao', models.TextField(blank=True, help_text='Ex: PIX C/C TROPICAL AGRO, PAGAMENTO EM ESPÉCIE', null=True, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cadastros.cliente', verbose_name='Cliente')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Cadastro')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento', '-id'],
                'indexes': [models.Index(fields=['data_pagamento', 'cliente'], name='financeiro__data_pa_ede97a_idx')],
            },
        ),
    ]
