# Generated by Django 4.2.27 on 2026-02-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(default=0, max_length=18, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
    ]
