# Generated by Django 4.2.27 on 2026-02-05 03:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(help_text='CPF ou CNPJ do cliente. Validação detalhada é feita no formulário.', max_length=18, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do motorista. Validação pode ser feita no forms.', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tipomadeira',
            name='preco_com_frete',
            field=models.DecimalField(decimal_places=2, help_text='Preço para romaneio com frete.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço com Frete por m³'),
        ),
        migrations.AlterField(
            model_name='tipomadeira',
            name='preco_normal',
            field=models.DecimalField(decimal_places=2, help_text='Preço para romaneio normal.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Normal por m³'),
        ),
    ]
