# Generated by Django 4.2.27 on 2026-02-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cliente_cpf_cnpj_alter_motorista_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ do cliente (opcional).', max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
