# Generated by Django 4.2.27 on 2026-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Romaneiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
            ],
            options={
                'verbose_name': 'Romaneiador',
                'verbose_name_plural': 'Romaneiadores',
                'ordering': ['nome'],
            },
        ),
    ]
